image: maven:3.5.3-jdk-8

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  untracked: true
  paths:
    - .m2/repository/

stages:
  - build
  - test
  - package
  - deploy

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -pl "!codegenerator.rest.karaf" clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -pl "!codegenerator.rest.karaf" test

package:
  stage: package
  script:
    - mvn $MAVEN_CLI_OPTS clean install -DskipTests
  only:
    - master

deploy:
  stage: deploy
  image: docker:dind
  script:
    - cd codegenerator.rest.karaf/target/
    - docker login -u $DOCKER_USER -p $DOCKER_PASSOWORD $DOCKER_SERVER 
    - docker build -t code.generator -t $DOCKER_SERVER/code.generator:$CI_COMMIT_REF_SLUG -t $DOCKER_SERVER/code.generator:latest .
    - docker push $DOCKER_SERVER/code.generator:$CI_COMMIT_REF_SLUG
    - docker push $DOCKER_SERVER/code.generator:latest
  only:
    - master

mirror-git:
  stage: deploy
  image: alpine
  cache: {}
  before_script:
    - apk update
    - apk add git
  script:
    - git clone --mirror ${CI_REPOSITORY_URL} project
    - cd project
    - git remote add activage ${ACTIVAGE_PROJECT_URL}.git
    - git push --mirror activage
    - cd -
    - git clone --mirror ${CI_REPOSITORY_URL/\.git/\.wiki\.git} wiki
    - cd wiki
    - git remote add activage ${ACTIVAGE_PROJECT_URL}.wiki.git
    - git push --mirror activage
