image: maven:3-jdk-8

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"

cache:
  paths:
    - .m2/repository/
    - codegenerator.rest.karaf/target

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS -pl "!codegenerator.rest.karaf" clean compile

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -pl "!codegenerator.rest.karaf" test

package:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS -fn install
  artifacts:
    paths:
      - codegenerator.rest.karaf/target/
  only:
    - master

deploy:
  stage: deploy
  image: docker:dind
  dependencies:
    - package
  script:
    - cd codegenerator.rest.karaf/target/
    - docker login -u $DOCKER_USER -p $DOCKER_PASSOWORD docker-activage.satrd.es 
    - docker build -t code.generator -t $DOCKER_SERVER/code.generator:$DOCKER_VERSION .
    - docker push $DOCKER_SERVER/code.generator:$DOCKER_VERSION
  only:
    - master